apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "pihole.fullname" . }}-dnsmasq
  labels:
    app: {{ template "pihole.name" . }}
    chart: {{ template "pihole.chart" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
data:
  02-custom.conf:
    address=/pi.hole/{{ .Values.host.ipv4 }}
