apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "pihole.fullname" . }}
  labels:
    app: {{ template "pihole.name" . }}
    chart: {{ template "pihole.chart" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ template "pihole.fullname" . }}
  template:
    metadata:
      labels:
        app: {{ template "pihole.fullname" . }}
    spec:
      dnsPolicy: "None"
      dnsConfig:
        nameservers:
        - 127.0.0.1
        - 1.1.1.1
        - 8.8.8.8
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        resources:
          limits:
            memory: 1Gi
        env:
        - name: 'ServerIP'
          value: {{ required "A valid .Values.host.ipv4 entry is required." .Values.host.ipv4 }}
        - name: 'DNS1'
          value: '1.1.1.1'
        - name: 'DNS2'
          value: '8.8.8.8'
        - name: 'VIRTUAL_HOST'
          value: 'pi.hole'
        ports:
        - name: http
          containerPort: 80
        - name: dns-tcp
          containerPort: 53
          protocol: TCP
        - name: dns-udp
          containerPort: 53
          protocol: UDP
        livenessProbe:
          httpGet:
            path: /
            port: http
        readinessProbe:
          httpGet:
            path: /
            port: http
        volumeMounts:
          - mountPath: "/etc/pihole"
            name: {{ template "pihole.fullname" . }}-pvc
            subPath: "pihole"
          - mountPath: "/etc/pihole/whitelist.txt"
            name: {{ template "pihole.fullname" . }}-lists
            subPath: whitelist.txt
          - mountPath: "/etc/pihole/adlists.list"
            name: {{ template "pihole.fullname" . }}-lists
            subPath: adlists.list
      volumes:
        - name: {{ template "pihole.fullname" . }}-lists
          configMap:
            name: {{ template "pihole.fullname" . }}-lists
        - name: {{ template "pihole.fullname" . }}-pvc
          persistentVolumeClaim:
            claimName: {{ template "pihole.fullname" . }}-pvc
