kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ template "pihole.fullname" . }}-pvc
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 5Gi
