apiVersion: v1
kind: Service
metadata:
  name: {{ template "pihole.fullname" . }}-udp
  labels:
    app: {{ template "pihole.name" . }}
    chart: {{ template "pihole.chart" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
spec:
  externalTrafficPolicy: Local
  type: "LoadBalancer"
  ports:
  - name: dns-udp
    port: 53
    targetPort: dns-udp
    protocol: UDP
  selector:
    app: {{ template "pihole.fullname" . }}
